name: Releases

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        run: pipx install uv

      - name: Run semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 22.0.6
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/exec@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
